services:
  leetcode_bot_deluxe:
    container_name: leetcode_bot_deluxe
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    image: leetcode_bot_deluxe
    env_file:
      - .env
    ports:
      - "${METRICS_PORT}:9091"
    networks:
      - leetcode_bot_network

networks:
  leetcode_bot_network:
    name: ${LEETCODE_BOT_NETWORK}
    external: true
